name: Generate Mihomo Rules

on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 1
#  push:
#    branches:
#      - main
#    paths-ignore:
#      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "private=https://raw.githubusercontent.com/Loyalsoldier/domain-list-custom/release/private.txt" >> $GITHUB_ENV
          echo "ads=https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt" >> $GITHUB_ENV
          echo "proxy=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.yaml" >> $GITHUB_ENV
          echo "proxy_ip=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml" >> $GITHUB_ENV
          echo "cn=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.yaml" >> $GITHUB_ENV
          echo "cn_ip=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP.yaml" >> $GITHUB_ENV
          echo "talkatone=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/Talkatone_Domain.yaml" >> $GITHUB_ENV
          echo "talkatone_ip=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/Talkatone_IP.yaml" >> $GITHUB_ENV
          echo "talkatonead=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/TalkatoneAD_Domain.yaml" >> $GITHUB_ENV
          echo "talkatonead_ip=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/TalkatoneAD_ip.yaml" >> $GITHUB_ENV
          echo "custom_direct=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/Custom_Direct_Domain.yaml" >> $GITHUB_ENV
          echo "custom_proxy=https://raw.githubusercontent.com/jovinleung/Rules/refs/heads/main/Custom/rules/Custom_Proxy_Domain.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Checkout
        uses: actions/checkout@main

      - name: Download and install Mihomo
        run: |
          wget -q --no-check-certificate https://github.com/MetaCubeX/mihomo/releases/download/v1.19.11/mihomo-linux-amd64-v1.19.11.deb
          sudo dpkg -i mihomo-linux-amd64-v1.19.11.deb
        shell: bash

      - name: Generate Rule Files
        run: |
          curl -sSL ${private} | awk -F ':' '/^full:/ {printf "  - |%s|\n", $2}' | sed "s/|/'/g" >> private.txt
          curl -sSL ${private} | awk -F ':' '/^domain:/ {printf "  - |+.%s|\n", $2}' | sed "s/|/'/g" >> private.txt
          curl -sSL ${cn} | grep -v '#' >> cn.txt
          curl -sSL ${proxy} | grep -v '#' >> proxy.txt
          curl -sSL ${ads} | \
          grep -E "^\|\|([a-zA-Z0-9.-]+\.[a-zA-Z]+)\^" | \
          sed "s/||/- '+./; s/\^$/'/" >> ads.txt
          curl -sSL ${cn_ip} | grep -v '#' >> cnip.txt
          curl -sSL ${proxy_ip} | \
          grep -v '#' | \
          grep -v 'DOMAIN-KEYWORD' | \
          grep -v ' IP-CIDR6' | \
          grep -v 'PROCESS-NAME' | \
          sed "s/^\s*- \s*IP-CIDR,/ - '/;s/$/'/" >> proxyip.txt
          curl -sSL ${talkatone} | grep -v '#' >> talkatone.txt
          curl -sSL ${talkatone_ip} | grep -v '#' >> talkatoneip.txt
          curl -sSL ${talkatonead} | grep -v '#' >> talkatonead.txt
          curl -sSL ${custom_direct} | grep -v '#' >> custom_direct.txt
          curl -sSL ${custom_proxy} | grep -v '#' >> custom_proxy.txt

      - name: Run MRS Script
        run: |
          chmod +x ./Custom/script/mrs_rules.sh
          ./Custom/script/mrs_rules.sh

      - name: Move Generated Files to Publish Directory
        run: |
          mkdir -p publish
          mv *.mrs publish/

      - name: Commit and Push MRS Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd publish
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git branch -M mrs
          git remote add origin https://github-action:$GITHUB_TOKEN@github.com/jovinleung/Rules.git
          git push -f -u origin mrs

      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
