name: Purge jsDelivr Cache

on:
  push:
    branches:
      - main
    paths:
      - 'Custom/config/**'
      - 'Custom/rules/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        env:
          REPO: jovinleung/Rules
        run: |
          echo "Purging jsDelivr cache for $REPO"
          for i in {1..3}; do
            echo "Attempt $i: Purging..."
            result=$(curl -s -X GET "https://purge.jsdelivr.net/gh/${REPO}")
            echo "$result"
            if echo "$result" | grep -q '"status": "finished"'; then
              echo "Purge succeeded."
              break
            else
              echo "Purge failed, retrying in 5s..."
              sleep 5
            fi
            if [ "$i" -eq 3 ]; then
              echo "Purge failed after 3 attempts."
              exit 1
            fi
          done

      - uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1